"""PostgreSQL schema as numbered migrations. `MIGRATIONS[n]` is applied once, in order, under a
`schema_version` table; a running engine only ever applies the versions it has not seen. Version 1
is the whole schema in its current shape (there is no ALTER history to replay: databases created
by the SQLite era are brought over by `sde_curation.import_sqlite`)."""

from __future__ import annotations

# One key for every engine process that runs migrations: two tasks booting at once serialise here.
MIGRATION_LOCK_KEY = 0x5DE_C0DE

V1 = """
CREATE TABLE collections (
  collection_id text PRIMARY KEY,
  name text NOT NULL,
  seed_url text NOT NULL,
  division text NOT NULL,
  document_type text,
  connector text NOT NULL,
  max_pages integer NOT NULL,
  status text NOT NULL,
  curation_stage text,
  needs_recuration boolean NOT NULL DEFAULT false,
  recuration_reason text,
  last_scraped_at timestamptz,
  created_at timestamptz NOT NULL,
  updated_at timestamptz NOT NULL,
  dump_count integer NOT NULL DEFAULT 0,
  delta_count integer NOT NULL DEFAULT 0,
  curated_count integer NOT NULL DEFAULT 0,
  last_run_id text,
  created_by text
);

CREATE TABLE status_history (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  collection_id text NOT NULL REFERENCES collections(collection_id) ON DELETE CASCADE,
  old_status text,
  new_status text NOT NULL,
  note text,
  at timestamptz NOT NULL,
  actor text
);
CREATE INDEX status_history_coll ON status_history (collection_id, id);

CREATE TABLE dump_urls (
  collection_id text NOT NULL REFERENCES collections(collection_id) ON DELETE CASCADE,
  url text NOT NULL,
  scraped_title text,
  full_text text,
  content_type text,
  depth integer,
  content_hash text,
  PRIMARY KEY (collection_id, url)
);

CREATE TABLE delta_urls (
  collection_id text NOT NULL REFERENCES collections(collection_id) ON DELETE CASCADE,
  url text NOT NULL,
  kind text NOT NULL,
  scraped_title text,
  title text,
  division text,
  document_type text,
  excluded boolean NOT NULL DEFAULT false,
  content_changed boolean NOT NULL DEFAULT false,
  edited_by text,
  title_ai text,
  division_ai text,
  document_type_ai text,
  title_ai_conf text,
  division_ai_conf text,
  document_type_ai_conf text,
  ai_model text,
  ai_content_hash text,
  PRIMARY KEY (collection_id, url)
);

CREATE TABLE curated_urls (
  collection_id text NOT NULL REFERENCES collections(collection_id) ON DELETE CASCADE,
  url text NOT NULL,
  scraped_title text,
  title text,
  division text,
  document_type text,
  excluded boolean NOT NULL DEFAULT false,
  content_hash text,
  edited_by text,
  PRIMARY KEY (collection_id, url)
);
-- V2 added `full_text` (the text the row was approved with; the export ships it); V9 moved it into
-- `page_text`, keyed by the `content_hash` that already fingerprinted it, so the dump and the
-- curated set share one copy of each page.

CREATE TABLE patterns (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  collection_id text NOT NULL REFERENCES collections(collection_id) ON DELETE CASCADE,
  type text NOT NULL,
  match text NOT NULL,
  value text,
  created_at timestamptz NOT NULL,
  created_by text,
  source text NOT NULL DEFAULT 'sme',
  UNIQUE (collection_id, type, match)
);

CREATE TABLE pattern_effects (
  pattern_id bigint NOT NULL REFERENCES patterns(id) ON DELETE CASCADE,
  collection_id text NOT NULL,
  url text NOT NULL,
  field text NOT NULL,
  PRIMARY KEY (pattern_id, url, field)
);
CREATE INDEX pattern_effects_coll_url ON pattern_effects (collection_id, url);

CREATE TABLE pattern_suggestions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  collection_id text NOT NULL REFERENCES collections(collection_id) ON DELETE CASCADE,
  type text NOT NULL,
  match text NOT NULL,
  value text,
  rationale text,
  matches integer NOT NULL DEFAULT 0,
  state text NOT NULL DEFAULT 'pending',
  source text NOT NULL DEFAULT 'llm',
  created_at timestamptz NOT NULL,
  decided_by text,
  accepted_as text,
  UNIQUE (collection_id, type, match)
);

CREATE TABLE index_runs (
  run_id text PRIMARY KEY,
  collection_id text NOT NULL REFERENCES collections(collection_id) ON DELETE CASCADE,
  target text NOT NULL,
  state text NOT NULL,
  exported integer NOT NULL DEFAULT 0,
  external_ref text,
  status jsonb,
  validation jsonb,
  validated_by text,
  error text,
  started_at timestamptz NOT NULL,
  finished_at timestamptz,
  started_by text
);
CREATE INDEX index_runs_coll ON index_runs (collection_id, started_at DESC);

CREATE TABLE job_runs (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  collection_id text NOT NULL REFERENCES collections(collection_id) ON DELETE CASCADE,
  kind text NOT NULL,
  state text NOT NULL,
  run_id text,
  external_ref text,
  progress jsonb NOT NULL DEFAULT '{}'::jsonb,
  error text,
  started_at timestamptz NOT NULL,
  finished_at timestamptz,
  started_by text
);
CREATE INDEX job_runs_coll ON job_runs (collection_id, id DESC);
CREATE INDEX job_runs_state ON job_runs (state, id);

CREATE TABLE users (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username text NOT NULL,
  password_hash text NOT NULL,
  role text NOT NULL DEFAULT 'curator',
  active boolean NOT NULL DEFAULT true,
  session_version integer NOT NULL DEFAULT 1,
  created_at timestamptz NOT NULL,
  updated_at timestamptz NOT NULL
);
-- usernames are unique regardless of case (the SQLite schema used COLLATE NOCASE)
CREATE UNIQUE INDEX users_username_lower ON users (lower(username));

-- append-only provenance ledger; no FK so it survives collection deletion
CREATE TABLE audit_log (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  at timestamptz NOT NULL,
  actor text NOT NULL,
  collection_id text,
  action text NOT NULL,
  detail text
);
CREATE INDEX audit_log_coll ON audit_log (collection_id, id DESC);
"""

# The curated set carries the page text it was approved with, so an export never depends on the
# dump still holding that crawl. Existing rows take the current dump text: before this column the
# export always shipped the dump text, so that is exactly what the index holds for them.
V2 = """
ALTER TABLE curated_urls ADD COLUMN full_text text;
UPDATE curated_urls c SET full_text = d.full_text
  FROM dump_urls d WHERE d.collection_id = c.collection_id AND d.url = c.url;
"""

# V3: URL identity and crawl failures in the diff — a delta may rename a curated row (same page,
# new spelling), tombstones carry the crawler's reason, curated rows the crawl could not fetch
# are kept and flagged, and the dump remembers what the crawler failed on and whether it was capped.
V3 = """
CREATE TABLE dump_failures (
  collection_id text NOT NULL REFERENCES collections(collection_id) ON DELETE CASCADE,
  url text NOT NULL,
  reason text NOT NULL,
  status integer,
  detail text,
  PRIMARY KEY (collection_id, url)
);
ALTER TABLE delta_urls ADD COLUMN renamed_from text;
ALTER TABLE delta_urls ADD COLUMN crawl_failure text;
ALTER TABLE curated_urls ADD COLUMN crawl_failure text;
ALTER TABLE collections ADD COLUMN last_crawl_capped boolean NOT NULL DEFAULT false;
"""

# V4: a Suggest metadata call that failed for a URL (after the in-job retry) is recorded on the row,
# so the failure is visible per URL and "Suggest missing" retries it; both clear on the next answer.
V4 = """
ALTER TABLE delta_urls ADD COLUMN ai_error text;
ALTER TABLE delta_urls ADD COLUMN ai_failures integer NOT NULL DEFAULT 0;
"""

# V5: "Regenerate duplicate titles" replaces a page's AI title with one that sets it apart from the pages it shared
# its title and document type with; the title it shared is kept, so the SME sees what it was.
V5 = """
ALTER TABLE delta_urls ADD COLUMN title_ai_before text;
"""

# V6: the collection_key / collection_name a collection is indexed under. Normally derived from the
# name (the COSMOS rule) and pinned by the first index run; set by hand when the folder differs.
V6 = """
ALTER TABLE collections ADD COLUMN index_key text;
ALTER TABLE collections ADD COLUMN index_name text;
"""

# V7: `curated_count` becomes the number of curated URLs that reach the index (the included ones),
# because that is the number the curator is told; `curated_rows` keeps the size of the whole set
# (included + excluded — the Curated URLs list shows both) for the checks that ask "has anything
# been promoted". `curated_changed_at` is when the curated set last changed: an index run started
# before it is behind the curated set, which is what the "needs re-indexing" chip reads.
V7 = """
ALTER TABLE collections ADD COLUMN curated_rows integer NOT NULL DEFAULT 0;
ALTER TABLE collections ADD COLUMN curated_changed_at timestamptz;
UPDATE collections c SET
  curated_rows = (SELECT COUNT(*) FROM curated_urls u WHERE u.collection_id = c.collection_id),
  curated_count = (SELECT COUNT(*) FROM curated_urls u WHERE u.collection_id = c.collection_id AND NOT u.excluded);
"""

# V8: the row was classified while the collection had a real division, so the model was never asked
# for one (`suggest_metadata_one` drops the field from the schema). Together with a division back at
# the General placeholder it is the one state that means "this row still owes a division and nobody
# has been asked": it can only arise once the curator puts the collection back to General, and it is
# what lets Suggest metadata ask for the divisions alone instead of re-classifying every field of
# every page. It does not collide with a suggestion the SME dismissed — that row was asked, and was
# never skipped.
V8 = """
ALTER TABLE delta_urls ADD COLUMN division_skipped boolean NOT NULL DEFAULT false;
"""

# V9: the page text is stored once, not twice. `dump_urls.full_text` and `curated_urls.full_text`
# held the same bytes for every URL whose curated row was approved with the text the dump still
# has — which is nearly all of them — so a collection cost two copies of its crawl in the database
# and the RDS volume grew at twice the rate the crawls did. Both tables already carry the
# `content_hash` that fingerprints exactly those bytes (`engine.text.content_hash`; V2 and
# `engine.diff.promote` keep it true of the curated row too), so it becomes the key of a
# content-addressed `page_text` table both sides point at. Nothing in the app's behaviour changes:
# a curated row still serves the text it was approved with, because a re-crawl that changes a page
# gives it a new hash and the old blob is kept until no row references it (`Database.gc_page_text`).
#
# Two pages whose text differs only in whitespace hash the same (the hash is of the normalised
# text) and so now share one blob: the raw spacing kept is whichever was ingested first. That is
# invisible to the index, which is the only reader.
#
# Storage note: DROP COLUMN does not free the TOAST the column pointed at, so the text is NULLed
# first — that makes the old TOAST rows dead and autovacuum returns them to the table's free space,
# which is what stops the volume growing. To hand the space back to the OS as well, run
# `make db-compact` (VACUUM FULL) in a maintenance window. Both the extraction and the NULLing
# happen in this one transaction, so the migration itself needs headroom for one more copy of the
# text while it runs: raise the volume ceiling before deploying it.
#
# Rows old enough to predate hashing have text but no hash, and the hash is now the only way to
# hold text — so they are given one here, computed the way `engine.text.content_hash` computes it
# (collapse whitespace runs, strip, sha256 of the UTF-8). PostgreSQL's `\s` and Python's
# `str.split()` disagree about a few exotic Unicode spaces, so such a row could come out with a
# hash Python would not have produced. That is harmless: the same expression keys the blob and
# stamps the row, so they always agree with each other, and the next crawl replaces the hash with
# a Python-computed one (at worst flagging the page as content-changed once, which for a row
# nobody ever hashed is the honest answer).
V9 = r"""
UPDATE dump_urls SET content_hash =
    encode(sha256(convert_to(btrim(regexp_replace(full_text, '\s+', ' ', 'g')), 'UTF8')), 'hex')
  WHERE content_hash IS NULL AND btrim(regexp_replace(full_text, '\s+', ' ', 'g')) <> '';
UPDATE curated_urls SET content_hash =
    encode(sha256(convert_to(btrim(regexp_replace(full_text, '\s+', ' ', 'g')), 'UTF8')), 'hex')
  WHERE content_hash IS NULL AND btrim(regexp_replace(full_text, '\s+', ' ', 'g')) <> '';
CREATE TABLE page_text (
  collection_id text NOT NULL REFERENCES collections(collection_id) ON DELETE CASCADE,
  content_hash text NOT NULL,
  full_text text NOT NULL,
  PRIMARY KEY (collection_id, content_hash)
);
INSERT INTO page_text (collection_id, content_hash, full_text)
  SELECT collection_id, content_hash, full_text FROM dump_urls
   WHERE content_hash IS NOT NULL AND full_text IS NOT NULL
  ON CONFLICT (collection_id, content_hash) DO NOTHING;
INSERT INTO page_text (collection_id, content_hash, full_text)
  SELECT collection_id, content_hash, full_text FROM curated_urls
   WHERE content_hash IS NOT NULL AND full_text IS NOT NULL
  ON CONFLICT (collection_id, content_hash) DO NOTHING;
CREATE INDEX dump_urls_hash ON dump_urls (collection_id, content_hash);
CREATE INDEX curated_urls_hash ON curated_urls (collection_id, content_hash);
UPDATE dump_urls SET full_text = NULL WHERE full_text IS NOT NULL;
UPDATE curated_urls SET full_text = NULL WHERE full_text IS NOT NULL;
ALTER TABLE dump_urls DROP COLUMN full_text;
ALTER TABLE curated_urls DROP COLUMN full_text;
"""

# Who is curating a collection: whoever last pressed Start curating / Check for changes /
# Re-curate everything (the recompute endpoint), so the dashboard's Curator filter follows the work
# rather than whoever added the collection. Existing rows take the last recompute in the audit log;
# a collection nobody has curated stays NULL and the dashboard falls back to `created_by`.
V10 = """
ALTER TABLE collections ADD COLUMN curated_by text;
UPDATE collections c SET curated_by = a.actor FROM (
  SELECT DISTINCT ON (collection_id) collection_id, actor FROM audit_log
   WHERE action IN ('recompute', 'recompute.all') AND collection_id IS NOT NULL
   ORDER BY collection_id, id DESC
) a WHERE a.collection_id = c.collection_id;
"""

MIGRATIONS: list[tuple[int, str]] = [(1, V1), (2, V2), (3, V3), (4, V4), (5, V5), (6, V6), (7, V7), (8, V8),
                                     (9, V9), (10, V10)]

# Every application table, parents before children (the order the importer copies them in, and
# the order TRUNCATE ... CASCADE does not care about).
TABLES = (
    "collections", "status_history", "page_text", "dump_urls", "dump_failures", "delta_urls", "curated_urls",
    "patterns", "pattern_effects", "pattern_suggestions", "index_runs", "job_runs", "users", "audit_log",
)

_VERSION_TABLE = (
    "CREATE TABLE IF NOT EXISTS schema_version ("
    "version integer PRIMARY KEY, applied_at timestamptz NOT NULL DEFAULT now())"
)


def pending(current: int) -> list[tuple[int, str]]:
    return [(v, sql) for v, sql in MIGRATIONS if v > current]


def migrate_sync(conn) -> int:
    """Apply missing migrations on a sync psycopg connection (importer, tests). Returns the
    resulting schema version. One transaction, serialised by an advisory lock."""
    with conn.transaction():
        conn.execute("SELECT pg_advisory_xact_lock(%s)", (MIGRATION_LOCK_KEY,))
        conn.execute(_VERSION_TABLE)
        current = conn.execute("SELECT COALESCE(MAX(version), 0) FROM schema_version").fetchone()[0]
        for version, sql in pending(current):
            conn.execute(sql)
            conn.execute("INSERT INTO schema_version (version) VALUES (%s)", (version,))
            current = version
    return current


async def migrate_async(conn) -> int:
    """Same as `migrate_sync` for an async connection (the engine at start-up)."""
    async with conn.transaction():
        await conn.execute("SELECT pg_advisory_xact_lock(%s)", (MIGRATION_LOCK_KEY,))
        await conn.execute(_VERSION_TABLE)
        cur = await conn.execute("SELECT COALESCE(MAX(version), 0) AS v FROM schema_version")
        row = await cur.fetchone()
        current = row["v"] if isinstance(row, dict) else row[0]
        for version, sql in pending(current):
            await conn.execute(sql)
            await conn.execute("INSERT INTO schema_version (version) VALUES (%s)", (version,))
            current = version
    return current
