"""PostgreSQL schema as numbered migrations. `MIGRATIONS[n]` is applied once, in order, under a
`schema_version` table; a running engine only ever applies the versions it has not seen. Version 1
is the whole schema in its current shape (there is no ALTER history to replay: databases created
by the SQLite era are brought over by `sde_curation.import_sqlite`)."""

from __future__ import annotations

# One key for every engine process that runs migrations: two tasks booting at once serialise here.
MIGRATION_LOCK_KEY = 0x5DE_C0DE

V1 = """
CREATE TABLE collections (
  collection_id text PRIMARY KEY,
  name text NOT NULL,
  seed_url text NOT NULL,
  division text NOT NULL,
  document_type text,
  connector text NOT NULL,
  max_pages integer NOT NULL,
  status text NOT NULL,
  curation_stage text,
  needs_recuration boolean NOT NULL DEFAULT false,
  recuration_reason text,
  last_scraped_at timestamptz,
  created_at timestamptz NOT NULL,
  updated_at timestamptz NOT NULL,
  dump_count integer NOT NULL DEFAULT 0,
  delta_count integer NOT NULL DEFAULT 0,
  curated_count integer NOT NULL DEFAULT 0,
  last_run_id text,
  created_by text
);

CREATE TABLE status_history (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  collection_id text NOT NULL REFERENCES collections(collection_id) ON DELETE CASCADE,
  old_status text,
  new_status text NOT NULL,
  note text,
  at timestamptz NOT NULL,
  actor text
);
CREATE INDEX status_history_coll ON status_history (collection_id, id);

CREATE TABLE dump_urls (
  collection_id text NOT NULL REFERENCES collections(collection_id) ON DELETE CASCADE,
  url text NOT NULL,
  scraped_title text,
  full_text text,
  content_type text,
  depth integer,
  content_hash text,
  PRIMARY KEY (collection_id, url)
);

CREATE TABLE delta_urls (
  collection_id text NOT NULL REFERENCES collections(collection_id) ON DELETE CASCADE,
  url text NOT NULL,
  kind text NOT NULL,
  scraped_title text,
  title text,
  division text,
  document_type text,
  excluded boolean NOT NULL DEFAULT false,
  content_changed boolean NOT NULL DEFAULT false,
  edited_by text,
  title_ai text,
  division_ai text,
  document_type_ai text,
  title_ai_conf text,
  division_ai_conf text,
  document_type_ai_conf text,
  ai_model text,
  ai_content_hash text,
  PRIMARY KEY (collection_id, url)
);

CREATE TABLE curated_urls (
  collection_id text NOT NULL REFERENCES collections(collection_id) ON DELETE CASCADE,
  url text NOT NULL,
  scraped_title text,
  title text,
  division text,
  document_type text,
  excluded boolean NOT NULL DEFAULT false,
  content_hash text,
  edited_by text,
  PRIMARY KEY (collection_id, url)
);
-- V2 adds `full_text` (the text the row was approved with; the export ships it)

CREATE TABLE patterns (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  collection_id text NOT NULL REFERENCES collections(collection_id) ON DELETE CASCADE,
  type text NOT NULL,
  match text NOT NULL,
  value text,
  created_at timestamptz NOT NULL,
  created_by text,
  source text NOT NULL DEFAULT 'sme',
  UNIQUE (collection_id, type, match)
);

CREATE TABLE pattern_effects (
  pattern_id bigint NOT NULL REFERENCES patterns(id) ON DELETE CASCADE,
  collection_id text NOT NULL,
  url text NOT NULL,
  field text NOT NULL,
  PRIMARY KEY (pattern_id, url, field)
);
CREATE INDEX pattern_effects_coll_url ON pattern_effects (collection_id, url);

CREATE TABLE pattern_suggestions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  collection_id text NOT NULL REFERENCES collections(collection_id) ON DELETE CASCADE,
  type text NOT NULL,
  match text NOT NULL,
  value text,
  rationale text,
  matches integer NOT NULL DEFAULT 0,
  state text NOT NULL DEFAULT 'pending',
  source text NOT NULL DEFAULT 'llm',
  created_at timestamptz NOT NULL,
  decided_by text,
  accepted_as text,
  UNIQUE (collection_id, type, match)
);

CREATE TABLE index_runs (
  run_id text PRIMARY KEY,
  collection_id text NOT NULL REFERENCES collections(collection_id) ON DELETE CASCADE,
  target text NOT NULL,
  state text NOT NULL,
  exported integer NOT NULL DEFAULT 0,
  external_ref text,
  status jsonb,
  validation jsonb,
  validated_by text,
  error text,
  started_at timestamptz NOT NULL,
  finished_at timestamptz,
  started_by text
);
CREATE INDEX index_runs_coll ON index_runs (collection_id, started_at DESC);

CREATE TABLE job_runs (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  collection_id text NOT NULL REFERENCES collections(collection_id) ON DELETE CASCADE,
  kind text NOT NULL,
  state text NOT NULL,
  run_id text,
  external_ref text,
  progress jsonb NOT NULL DEFAULT '{}'::jsonb,
  error text,
  started_at timestamptz NOT NULL,
  finished_at timestamptz,
  started_by text
);
CREATE INDEX job_runs_coll ON job_runs (collection_id, id DESC);
CREATE INDEX job_runs_state ON job_runs (state, id);

CREATE TABLE users (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username text NOT NULL,
  password_hash text NOT NULL,
  role text NOT NULL DEFAULT 'curator',
  active boolean NOT NULL DEFAULT true,
  session_version integer NOT NULL DEFAULT 1,
  created_at timestamptz NOT NULL,
  updated_at timestamptz NOT NULL
);
-- usernames are unique regardless of case (the SQLite schema used COLLATE NOCASE)
CREATE UNIQUE INDEX users_username_lower ON users (lower(username));

-- append-only provenance ledger; no FK so it survives collection deletion
CREATE TABLE audit_log (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  at timestamptz NOT NULL,
  actor text NOT NULL,
  collection_id text,
  action text NOT NULL,
  detail text
);
CREATE INDEX audit_log_coll ON audit_log (collection_id, id DESC);
"""

# The curated set carries the page text it was approved with, so an export never depends on the
# dump still holding that crawl. Existing rows take the current dump text: before this column the
# export always shipped the dump text, so that is exactly what the index holds for them.
V2 = """
ALTER TABLE curated_urls ADD COLUMN full_text text;
UPDATE curated_urls c SET full_text = d.full_text
  FROM dump_urls d WHERE d.collection_id = c.collection_id AND d.url = c.url;
"""

MIGRATIONS: list[tuple[int, str]] = [(1, V1), (2, V2)]

# Every application table, parents before children (the order the importer copies them in, and
# the order TRUNCATE ... CASCADE does not care about).
TABLES = (
    "collections", "status_history", "dump_urls", "delta_urls", "curated_urls", "patterns",
    "pattern_effects", "pattern_suggestions", "index_runs", "job_runs", "users", "audit_log",
)

_VERSION_TABLE = (
    "CREATE TABLE IF NOT EXISTS schema_version ("
    "version integer PRIMARY KEY, applied_at timestamptz NOT NULL DEFAULT now())"
)


def pending(current: int) -> list[tuple[int, str]]:
    return [(v, sql) for v, sql in MIGRATIONS if v > current]


def migrate_sync(conn) -> int:
    """Apply missing migrations on a sync psycopg connection (importer, tests). Returns the
    resulting schema version. One transaction, serialised by an advisory lock."""
    with conn.transaction():
        conn.execute("SELECT pg_advisory_xact_lock(%s)", (MIGRATION_LOCK_KEY,))
        conn.execute(_VERSION_TABLE)
        current = conn.execute("SELECT COALESCE(MAX(version), 0) FROM schema_version").fetchone()[0]
        for version, sql in pending(current):
            conn.execute(sql)
            conn.execute("INSERT INTO schema_version (version) VALUES (%s)", (version,))
            current = version
    return current


async def migrate_async(conn) -> int:
    """Same as `migrate_sync` for an async connection (the engine at start-up)."""
    async with conn.transaction():
        await conn.execute("SELECT pg_advisory_xact_lock(%s)", (MIGRATION_LOCK_KEY,))
        await conn.execute(_VERSION_TABLE)
        cur = await conn.execute("SELECT COALESCE(MAX(version), 0) AS v FROM schema_version")
        row = await cur.fetchone()
        current = row["v"] if isinstance(row, dict) else row[0]
        for version, sql in pending(current):
            await conn.execute(sql)
            await conn.execute("INSERT INTO schema_version (version) VALUES (%s)", (version,))
            current = version
    return current
